set-option -g status-position top

# Make the status line pretty and add some modules
set -g status-justify "absolute-centre"
set -g status-style "bg=default"

# grab color-variables from different file
if-shell '[ -f ~/.config/tmux/colors-catcyber.conf ]' "source-file ~/.config/tmux/colors-catcyber.conf"

# main design tweaks!
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=default,bold]   #S },#{#[bg=default,fg=#{@thm_red},bold]   #I }}"
set -ga status-left "#[bg=default,fg=#{@thm_overlay0}]│"
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=default,bold]   #S },#{#[bg=default,fg=#{@thm_red},bold]   #S }}"
set -ga status-left "#[bg=default,fg=#{@thm_overlay0}]│"
set -ga status-left "#[bg=default,fg=#{@thm_green},bold]   #{pane_current_command} "
set -ga status-left "#[bg=default,fg=#{@thm_overlay0}]│"
set -ga status-left "#[bg=default,fg=#{@thm_blue},bold]   #{=/-10/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# right side
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=default,fg=#{@thm_green},bold]  #(uptime | awk '{print $3}' | tr -d ',') "
set -ga status-right "#[bg=default,fg=#{@thm_overlay0}]│"
set -ga status-right " #[fg=#{@thm_green},bold]  #W "
set -ga status-right "#[bg=default,fg=#{@thm_overlay0}]│"
set -ga status-right "#[bg=default,fg=#{@thm_blue},bold]  %H:%M "

# panes borders
setw -g pane-border-style "fg=#{@thm_overlay0}"
setw -g pane-active-border-style "fg=#{@thm_red}"
setw -g pane-border-lines single

# windows icons
set -g window-status-format '#{?#{==:#{pane_current_command},zsh},  ,#{?#{==:#{pane_current_command},nvim},  ,#{?#{==:#{pane_current_command},git}, 󰊢 ,#{?#{==:#{pane_current_command},htop},  ,#{?#{==:#{pane_current_command},python}, 󰌠 ,󰘧 }}}}}'
set -g window-status-current-format '#{?#{==:#{pane_current_command},zsh},  ,#{?#{==:#{pane_current_command},nvim},  ,#{?#{==:#{pane_current_command},git}, 󰊢 ,#{?#{==:#{pane_current_command},htop},  ,#{?#{==:#{pane_current_command},python}, 󰌠 ,󰘧 }}}}}'

set -g window-status-style "bg=default,fg=#{@thm_overlay0}"
set -g window-status-current-style "bg=default,fg=#{@thm_peach},bold"
