#
# +---------+
# | GENERAL |
# +---------+
#

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# Change prefix key to Ctrl-s
# .. C-b is ok, but not usually comfy
# .. C-a is mess with other stuff
# .. C-s smt mess with other stuff
# ? ` -> not sure
set-option -g prefix C-Space
unbind-key C-b
bind-key C-s send-prefix

# Keymaps
source-file ~/.config/tmux/keymaps.conf
source-file ~/.config/tmux/wsl-fix.conf

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Enable system clipboard
set-option -g set-clipboard on

# Some tweaks for image preview
set -gq allow-passthrough on
set -g visual-activity off

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# enable if -> u wan't to name windows manually by <command>+,
# set-option -g allow-rename off

#
# +---------------+
# | DESIGN TWEAKS |
# +---------------+
#

set -g default-terminal "tmux-256color"

source-file ~/.config/tmux/statusline.conf

#
# +----------------------+
# | Better vim-like copy |
# +----------------------+
#

set -g @plugin 'tmux-plugins/tmux-yank'

# set vi-mode
set-window-option -g mode-keys vi

# keymaps
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#
# +--------------+
# | Base plugins |
# +--------------+
#

# press: <prefix> + F
set -g @plugin 'sainnhe/tmux-fzf'

#
# +--------------+
# | Init plugins |
# +--------------+
# > don't forget to press Ctrl+I in tmux -> to install plugins
#

# REQUIRED for plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# REQUIRED for plugin manager
run '~/.tmux/plugins/tpm/tpm'

#
# +-------------+
# | After-fixes |
# +-------------+
#

# catpuccin statusline transparency
set -g status-bg default
set -g status-style bg=default
